# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('file', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
            ],
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('file', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
            ],
        ),
    ]
