# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcontent',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.Category'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='community.Category'),
        ),
    ]
