# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20170422_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.CharField(max_length=255, verbose_name='nome')),
                ('image', models.FileField(upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
                ('hide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.CharField(max_length=255, verbose_name='nome')),
                ('image', models.FileField(upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
                ('hide', models.BooleanField(default=False)),
            ],
        ),
    ]
