# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_event_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='video_id',
            field=models.CharField(default='', max_length=255, verbose_name='video_id'),
            preserve_default=False,
        ),
    ]
