# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_videocontent_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='video_id'),
        ),
    ]
